### ISSUE TITLE
Shopify POS 7.x cart UI issue when using App Bridge Cart.Action.ADD_LINE_ITEM

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#114]
## Describe the bug
Sometimes when adding products performing: 

```
        cart.dispatch(Cart.Action.ADD_LINE_ITEM, {
        data: {
            variantId:parseInt(variantId),
            quantity: 1
        }
        });  
```

The Shopify POS cart UI will only show the variantId in the main POS cart. 

### To Reproduce

I am not sure how to reliably reproduce this yet, but this is an image a customer sent to me, and I have also seen it happen on occasion in my own testing. 

### Expected behaviour

The product's title and variant title should appear in the Shopify POS cart instead of the variantId

## Contextual information

I believe it's happening on apps that use both versions below, at least definitely on the one using 1.25.0

- `@shopify/app-bridge` @ `1.25.0`
- `@shopify/app-bridge` @ `2.0.0`
- 
## Platform

- OS: iOS 15.x
- OS Version: 
- App: POS Next
- 
![Image (1)](https://user-images.githubusercontent.com/46724607/173240557-d02fd91b-809b-4379-aa3e-2b34ab86b093.jpeg)

**Comment by samiulmonir06** [comment]
@derrickrc : We could not reproduce the issue. Can you please give some more details to investigate:

1. The store domain
2. User and which products they have added
3. Which POS version they are using?

**Comment by vctrchu** [comment]
Update:
- There is an issue where when products are added to the cart, the variant id / product id appears as the line item title instead of the actual title. 
-  Pretty hard bug to reproduce but I will be pairing with Sam tomorrow to see if I missed anything and then will make a decision to backlog it until proper reproduction steps are given.

**Comment by vctrchu** [comment]
After pairing:
- I have messaged Derrick to receive more GraphQL Json responses to compare possible discrepancies.
- Merchant should update to the most recent POS to see if problems still exist.
- Best course of action is to backlog this item until more suitable reproduction steps are in place.

**Comment by derrickrc** [comment]
It seems to be a timing issue as if you wait a little bit, eventually the product IDs will change to the correct product text in the cart UI.

**Comment by derrickrc** [comment]
@vctrchu thanks, I will check in 7.6.0.

**Comment by vctrchu** [comment]
Thanks for the update. I will add this to our backlog.

**Comment by derrickrc** [comment]
@vctrchu just bumping this, thanks!

**Comment by vctrchu** [comment]
Hi @derrickrc a fix has been merged however Shopify POS is currently on a code freeze until the beginning of January due holiday season. Thanks for your patience.

**Comment by derrickrc** [comment]
Thank you @vctrchu !

**Comment by derrickrc** [comment]
@vctrchu any update on this? We continue to receive tickets about this, the issue persists.

**Comment by vctrchu** [comment]
Hi Derrick, apologies for the delay. Our team can take a look soon, I want to confirm is this [video](https://github.com/Shopify/shopify-app-bridge/issues/114#issuecomment-1185903782) accurate of what the issue is? What app is this happening on?
