### ISSUE TITLE
Loading embedded app in test store causes exception in Chrome console.

### ISSUE THREAD

**Issue by ianjosephwilson** [Shopify/shopify-app-bridge#123]
## Describe the bug

Loading embedded app in test store causes exception in Chrome console.

```text
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.example.com') does not match the recipient window's origin ('https://example.myshopify.com').
```

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />                <script src="https://unpkg.com/@shopify/app-bridge@3.1.1"></script>
	
	<script>
         var appConfig = {"apiKey": "example-api-key"};
  	 var AppBridge = window['app-bridge'];
         var ourApp = AppBridge.createApp({
             apiKey: appConfig.apiKey,
             host: new URL(location).searchParams.get("host"),
         });

	</script>      
    <body>Testing</body>
</html>
```
### To Reproduce

Steps to reproduce the behaviour:

1. Click install app in shopify.dev
2. Click select store
3. Select example-store
4. Page loads (because its already installed)
5. Exception is in dev console

## Packages and versions

- `@shopify/app-bridge` @ `3.1.1`

## Platform

- OS: Debian Linux
- OS Version: 
- App: Chrome

This exception appears to not occur in `3.1.0` via `https://unpkg.com/@shopify/app-bridge@3.1.0`.

**Comment by charlesdobson** [comment]
Hi, Ian!

Thanks for reporting this. We have a ticket logged to solve this issue. You can safely ignore the console warning for now if you only see it once per page load.

**Comment by ianjosephwilson** [comment]
@rsbowers I'm only making a custom app for a single shop.  I just was having other problems and thought it was related but it just seems to be some sort of bug in the bundle itself that doesn't actually affect the library or my code.

The error only occurs the first time the app bridge library is loaded when embedded.  As I move around in the SPA the library isn't reloaded so the error does not occur.  It does seem to occur multiple times before the library re-embeds after returning from oauth where the SPA skeleton is loaded without the iframe.  So maybe it is just polling for the parent frame.

I think certain misconfigured app settings or iframe security settings can trigger the same bug when you ask the parent iframe (shopify) for a JWT to send back to your backend because it uses postMessage to communicate with the parent iframe.  At least as I understand it.  So it would look like the same error but source of the error would completely different.  I don't anything about the approval process though.

**Comment by ianjosephwilson** [comment]
Seems to be the same as #127

**Comment by agrohs** [comment]
It looks like app-bridge 3.1.3 was published this morning (`https://www.npmjs.com/package/@shopify/app-bridge/v/3.1.3`), just checking if that contained the fix for this by chance?

**Comment by agrohs** [comment]
Amazing news, thanks @henrytao-me!

**Comment by henrytao-me** [comment]
@agrohs The issue is fixed. Can you check it? I close this ticket for now 🙇

**Comment by rsbowers** [comment]
> @agrohs The issue is fixed. Can you check it? I close this ticket for now 🙇

I'm having issues with 3.1.3.  I scaffolded a fresh node app via the CLI, then upgraded the the following packages to 3.1.3: @shopify/app-bridge, @shopify/app-bridge-react, @shopify/app-bridge-utils.

Trying to run this app fails during the auth flow. `InvalidOAuthError: Invalid OAuth callback.`. I don't get this error with 3.1.0.

Is there something else I need to do? @henrytao-me

**Comment by ianjosephwilson** [comment]
I'm only using `@shopify/app-bridge` and `@shopify/app-bridge-utils` but upgrading to `3.1.3` has stopped this error from occurring once AppBridge redirects into the iframe.  The same error still shows before the redirect occurs but I think maybe that was always happening.

**Comment by henrytao-me** [comment]
@ianjosephwilson 

> The same error still shows before the redirect occurs but I think maybe that was always happening.

Can you share the error message? When the embedded app is initialized (call createApp) outside of Shopify context (outside of iframe on desktop), it will try to redirect back to Shopify. However, other part of your app might try to dispatch some App Bridge action which could be this case. You can try wrap your app inside [`isShopifyEmbedded`](https://shopify.dev/apps/tools/app-bridge/methods#platform-methods). I suspect the error will go away.

**Comment by henrytao-me** [comment]
@rsbowers I just try a new app via `yarn create @shopify/app` with App Bridge 3.1.3, it works fine for me without the auth issue. I think you have different issue but it would be nice to have more details in order to investigate. 

Also, you don't have to consume latest version of App Bridge in order to have the fix in this issue. It should work for all version of App Bridge.

**Comment by ianjosephwilson** [comment]
@henrytao-me 
```MessageTransport.js:135 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://exampleshop.myshopify.com') does not match the recipient window's origin ('https://example.com').```

I get the error 3 times if I just call createApp.  Maybe I'm doing something else wrong.  With forceRedirect set to true then I see the error 3 times and then the page redirects as it should.  So its just a non-blocking error again but if something else was wrong it would be confusing.

**Comment by henrytao-me** [comment]
@ianjosephwilson I see what you mean. I think I know why. I will test and push a fix tomorrow.

**Comment by henrytao-me** [comment]
Hi @agrohs @ianjosephwilson App Bridge 3.1.4 is out. The invalid origin should be fixed now if you consume the latest version. Let me know how it goes 🙇

**Comment by ianjosephwilson** [comment]
@henrytao-me This error seems like the priority zero at this point but if I set `forceRedirect` to `false` it still occurs, same message 3 times.  If I turn on `forceRedirect: true` or just leave it out because it is default then **no errors** and redirect occurs.  They don't show in the console with preserve log checked either so I don't think they are flashing by I think they just don't happen for some reason.  If server side redirection is going to be blessed soon then seems this is all moot?
