### ISSUE TITLE
App-bridge cnd breaks npm app-bridge navigation menu

### ISSUE THREAD

**Issue by PhiloNL** [Shopify/shopify-app-bridge#267]
## Describe the bug

I've been using both versions of app bridge, `@shopify/app-bridge` and. `cdn.shopify.com/shopifycloud/app-bridge.js`.
The CDN version I use for Toast and the resource picker. The NPM version I use for creating a navigation menu (`actions.NavigationMenu.create()`). This has always worked fine.

Starting this evening, the navigation menu renders but the links no longer work.

### To Reproduce

1. Launch an app that uses both the NPM and CDN app-bridge but uses the npm package to build the navigation using:
```js
     const navigationMenu = actions.NavigationMenu.create(app, {
            items: [ /... ]
        });
```
2. Navigate between pages and notice the page does not change.

### Expected behaviour

It should navigate between pages that I click in the navigation menu.

## Contextual information

Can we please get a CDN-versioned app bridge like the NPM package?

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `https://unpkg.com/@shopify/app-bridge@3.7.9/umd/index.js`
- `https://unpkg.com/@shopify/app-bridge-utils@3.5.1/umd/index.js`

## Platform

- OS: MacOS
- OS Version: 13.3.1
- App: Chrome

**Comment by PRS03** [comment]
+1

**Comment by ryanrphillips** [comment]
Did you confirm that the issue is caused by loading the CDN version of app bridge alongside the NPM version? There was an issue with the sidebar navigation yesterday that appears to have been resolved about 10 hours ago.

cc @henrytao-me

**Comment by PhiloNL** [comment]
@ryanrphillips I just gave it another try and the issue still persists, unfortunately. 

One issue seems to be resolved though; when you clicked the app itself in the sidebar from an app subpage it would not go to the root page.

**Comment by neoanic** [comment]
+1

**Comment by AgneshV** [comment]
I've also faced the same issue, When I click on the app itself in the sidebar from an app subpage it does not go to the root page. Have any solution for this?

**Comment by henrytao-me** [comment]
While we recommend to use Navigation Menu in App Bridge CDN, if you still want to use it from npm version, you need to disable it in App Bridge CDN. You can do it via meta tag

```
<meta name="shopify-disabled-features" content="navigation-menu" />
```

See https://shopify.dev/docs/api/app-bridge-library/reference/config#setting-config-values-disabledfeatures

**Comment by luizfaro** [comment]
> While we recommend to use Navigation Menu in App Bridge CDN, if you still want to use it from npm version, you need to disable it in App Bridge CDN. You can do it via meta tag
> 
> ```
> <meta name="shopify-disabled-features" content="navigation-menu" />
> ```
> 
> See https://shopify.dev/docs/api/app-bridge-library/reference/config#setting-config-values-disabledfeatures

Hello @henrytao-me !

Is there a list of possible values for the "shopify-disabled-features" meta tag? 
I am using AppBridge both CDN and npm package (as per https://github.com/Shopify/shopify-app-bridge/issues/194#issuecomment-2035257323), and I would like to disable the CDN features I have not yet migrated from the npm version...

Thank you!
