### ISSUE TITLE
Shopify App Bridge unable to access Cart on Android Shopify POS

### ISSUE THREAD

**Issue by rafaelsorto** [Shopify/shopify-app-bridge#93]
## Describe the bug

Checking for App features on Shopify POS Android returns false for every Cart Action. The keys and values are veriy different when comparing the ones on Android POS against the ones on iOS POS 

- Android List of Cart features
![IMG_20220128_161454016](https://user-images.githubusercontent.com/177517/151629186-549e3929-d2c7-4272-98bf-194ad6eec2d1.jpg)

- iOS List of Cart Features
![IMG_20220128_161509504_HDR](https://user-images.githubusercontent.com/177517/151629190-d9a6f4e8-2fac-4176-ba41-72a0b5b2e54a.jpg)

We are currently unable to fetch the cart or to add any items as it returns the Error Permission Denied. I see there is another Issue reported [#87](https://github.com/Shopify/shopify-app-bridge/issues/87) mentioning that on iOS the values are different but it seems this is a recent update on Shopify App Bridge that has not actually been propagated to the POS Apps? Or something similar?

### To Reproduce

Steps to reproduce the behaviour:

1. Create an app that uses Shopify App Bridge v2 and add it to the Android POS Smartgrid.
2. Launch the app from the smart grid list
3. See error when trying to access the Cart Fetch or Dispatch actions

### Expected behaviour

An app with Shopify App Bridge 2.0 should be able to Read and Add Items to the Cart

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

"@shopify/app-bridge": "^2.0.7",
"@shopify/app-bridge-react": "^2.0.7",
"@shopify/polaris": "^6.6.0",

## Platform

- OS: [Android]
- OS Version: [11]
- App: [Shopify POS 4.32.0]

### Additional context

We were having the issues to Access the Cart also on Shopify App Bridge v1 but I thought that this would not be a problem on v2 and updated everything to work on v2 but the problem persits. The problem is only on Android, the issue is not present on iOS we can read and put items in the Cart.

**Comment by AaronSpringut** [comment]
Hi all,

We've identified the issue here. A bug fix should be available in the next 10 days.

In the meantime ZainManji's solution to hardcode "FETCH", which is Cart.ActionType.FETCH without it's prefix, can be used as a short term workaround.

Best,
Aaron

**Comment by rafaelsorto** [comment]
I'm not sure if that is the solution for this report. I've tried to force the action to ADD_LINE_ITEMS and it still reports that it is Forbidden. It seems the keys are different in Android vs iOS, as you guys said one has APP::XXX::YYY and the other one only has YYY, but also if you notice everything in Android is reported as false in the permissions. I think if I still hardcode the FETCH or ADD_LINE_ITEM because the permission is Denied it reports Forbidden.

**Comment by henrytao-me** [comment]
Hi @rafaelsorto, can you check it again? This should be fixed now because we send both types (with and without prefix `APP::`)

**Comment by rafaelsorto** [comment]
Thank you @henrytao-me this issue is fixed! Thank you and everyone involved!

**Comment by mrniamster** [comment]
@henrytao-me 

Still facing the issue ,

Working on android but not on Ios,

Here is the code :

```
function getCart(){
   
    var  c = new Promise((rs,rj)=>{
    
        const unsubscribe = app.subscribe(Features.ActionType.UPDATE, function () { 
  app.featuresAvailable(Group.Cart).then((features) => {
     
    const hasFetchCart = features.Cart[Cart.Action.FETCH]; 
    
    if (hasFetchCart) { 
      unsubscribe(); 
      const cart = Cart.create(app);
      cart.subscribe(Cart.Action.UPDATE, payload => { 
       // console.log({cart: { payload }});
       rs({cart: { payload }})
      });
      cart.dispatch(Cart.Action.FETCH);
    } 
  }); 
});
    })
    return c;
}
```

**Comment by henrytao-me** [comment]
@mrniamster the reason why it doesn't work on iOS because iOS dispatch cart features available before your app calls `app.subscribe(Features.ActionType.UPDATE`. Therefore, there is no update callback after your app is loaded. On Android, it's slower than iOS. So often time, you have the callback.

Our recommendation for this is to do double checks. See https://github.com/Shopify/shopify-app-bridge/issues/105#issuecomment-1106651032.
